services:
  # MySQL 컨테이너 설정
  mysql:
    image: mysql:8.0
    container_name: velog-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: velog
      TZ: Asia/Seoul
    ports:
      - "3306:3306"
    # Volumn 설정
    volumes:
      - mysql_data:/var/lib/mysql
    # Health Check 설정
    healthcheck:
      test: ["CMD-SHELL", "MYSQL_PWD=${DB_PASSWORD} mysqladmin ping -h localhost -uroot"]
      interval: 5s # 5초마다 체크
      timeout: 3s # 5초 안에 응답 없으면 실패
      retries: 10 # 5번 재시도
    networks:
      - backend-network

  # Redis 컨테이너 설정
  redis:
    image: redis:7-alpine
    container_name: velog-redis
    restart: unless-stopped
    # 패스워드 추가
    command: ["redis-server", "--appendonly", "yes", "--requirepass", "${REDIS_PASSWORD}"]
    ports:
      - "6379:6379"
    # Volumn 설정
    volumes:
      - redis_data:/data
    # Health Check 설정
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping"]
      interval: 5s
      timeout: 3s
      retries: 10
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge

# 볼륨 정의
volumes:
  mysql_data:
  redis_data: