spring:
  datasource:
    url: jdbc:mysql://localhost:3306/velog?useSSL=true&allowPublicKeyRetrieval=true&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: root
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

    hikari:
      maximum-pool-size: 6
      minimum-idle: 6
      connection-timeout: 30000 # 30초

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: &{REDIS_PORT:6379}
      password: ${REDIS_PASSWORD}

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${GMAIL_USERNAME}
    password: ${SMTP_PWD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc.time.zone: Asia/Seoul

jwt:
  secret: ${JWT_SECRET_KEY}
  atk-exp-min: ${JWT_ACCESS_TOKEN_EXPIRATION_MINUTES:30}
  rtk-exp-week: ${JWT_REFRESH_TOKEN_EXPIRATION_WEEKS:2}